### ISSUE TITLE
using builtin MediaPlayer

### ISSUE THREAD

**Issue by rajesh-battala** [de-live-gdev/cherrymusic_android#1]
Hi, 
Great to see Android App for the Cherrymusic.
I have downloaded your apk. When I was going through code its using webview instead of mediaPlayer. 
Are there any issues to use buitlin mediaPlayer and play file using setStreamurl.?
will it be possible to use it like above?

**Comment by de-live-gdev** [comment]
Hi Rajesh,
I don't know if it will work, like you want, but it will make the whole thing more complicated, because you have to deal a lot with JS, and that makes problems on some devices.  
For example you would have to hide all playing bars, and filter out the file URLs, but I don't know if it would just work to set the url to it, maybe Headers and cookies need also to be added.

**Comment by gsantner** [comment]
@rajesh-battala 
If you are still using the app: I update the app, replaced most stuff. The update should be out soon on F-Droid.

**Comment by rajesh-battala** [comment]
Hi Gregor Santner,

Thanks for the update.

Thanks
Rajesh Battala.

On May 30, 2017 4:11 PM, "Gregor Santner" <notifications@github.com> wrote:

@rajesh-battala <https://github.com/rajesh-battala>
If you are still using the app: I update the app, replaced most stuff. The
update should be out soon on F-Droid.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gsantner/cherrymusic-android/issues/1#issuecomment-304840727>,
or mute the thread
