### ISSUE TITLE
offline streaming

### ISSUE THREAD

**Issue by bastian94** [de-live-gdev/cherrymusic_android#4]
Hey I am wondering if it's possibly to use this application to cache the playlist for offline streaming? If this is not possibly it would be a really nice feture to have

**Comment by de-live-gdev** [comment]
Hi @bastian94 ;
No it's not easily possible, because this just uses the webinterface of your cherrymusic instance.  
More advanced things require a good Cherrymusic API (which is currently not implement/not ready), and an app accessing the API. Also/But converting the app to something that communicates with the API would take a lot of time, which I appareantly don't have and won't invest, because there are quite many other streaming solutions (also Open-Source ones) which got this already implemented.

**Comment by gsantner** [comment]
@bastian94 
If you are still using the app: I update the app, replaced most stuff. The update should be out soon on F-Droid.
